source "https://rubygems.org"

ruby "3.4.5"

gem "rails", "~> 8.0.2"
gem "pg", "~> 1.6"
gem "puma", ">= 6.4"
gem "redis", "~> 5.4"
gem "sidekiq", "~> 7.3"
gem "connection_pool", "< 3"
gem "rack-cors", "~> 2.0"
gem "bcrypt", "~> 3.1"
gem "rotp", "~> 6.3"

group :development, :test do
  gem "rspec-rails", "~> 7.1"
  gem "rubocop", require: false
end
