#!/bin/sh
set -eu

: "${APP_DATABASE_USER:=crystell_app}"
: "${APP_DATABASE_PASSWORD:=change-me-local-only}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = '${APP_DATABASE_USER}') THEN
    CREATE ROLE ${APP_DATABASE_USER} LOGIN PASSWORD '${APP_DATABASE_PASSWORD}' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_DATABASE_USER};
GRANT USAGE ON SCHEMA public TO ${APP_DATABASE_USER};
EOSQL
